### ISSUE TITLE
Enable support for port forwarding on AWS SSM managed instances

### ISSUE THREAD

**Issue by djselzlein** [mmmorris1975/ssm-session-client#15]
I see that currently the port forwarding supports only EC2 instance IDs, per https://github.com/mmmorris1975/ssm-session-client/tree/main/examples/port-forwarder.
When I try using a managed instance ID I get the following error:
```
./port-forwarder mi-0f6abc5d244c338a1:9999
2024/09/02 16:04:49 no instances returned from lookup
```

It looks to me like a limitation of the target_resolver logic only since when I updated the regular expression there to allow `mi-` instance identifiers (https://github.com/djselzlein/ssm-session-client/commit/73bbbab717ce5e60471de04c4c77521afa54f8bf) it worked for me.

Would you be able to incorporate this on the repo?

**Comment by mmmorris1975** [comment]
Tagged as v0.401.1
