### ISSUE TITLE
Not working as proxy host

### ISSUE THREAD

**Issue by danquack** [mmmorris1975/ssm-session-client#2]
@mmmorris1975 @alwaysshrek
I stumbled upon this project and reading through the documentation, I think it might be good for my go tests on an app I have deployed behind an ssm proxy host. I may not be using this right, but I wanted to at least reach out and see if this is a good use case, and to help figure out what I may be doing wrong?

Currently I have my CI job create a sub shell and that just ssh into the box, using the ssh config and running `ssh i-1234567890`:
```
Host I-*
  User ssm-user
  Loglevel QUIET
  DynamicForward 12351
  ProxyCommand ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```

Attempting to use this library, I used the following code:
```go
cfg, err := config.LoadDefaultConfig(context.Background())
if err != nil {
    log.Fatal(err)
}
ssmclient.SSHSession(cfg, &ssmclient.PortForwardingInput{
   Target:    "i-1234567890",
   LocalPort: 12351,
})
```

My goal is to add a test in my codebase which is something like:
```go
os.Setenv("HTTP_PROXY", "socks5://127.0.0.1:12351")
resp, err := http.Get("http://ip.jsontest.com")
if err != nil {
    log.Fatal(err)
}
```
or to be able to execute a command on the box and get the output back to my go code:
```bash
curl http://ip.jsontest.com
```

I run into a few issues

1. Protocol Mismatch:
```shell
2021/06/10 16:08:05 waiting for handshake
2021/06/10 16:08:05 handshake complete
SSH-2.0-OpenSSH_7.4

Protocol mismatch.
```
2.  Nothing listening on 12351 for me to proxy to

Overall, I am wondering: is this meant for what I am describing, or did I misinterpret it? If it is, can you help me in what I am doing wrong to achieve this goal?

Some maybe helpful info:

- go version go1.16.3 darwin/amd64
- session-manager-plugin version  1.2.54.0
- app versions:
    - github.com/mmmorris1975/ssm-session-client v0.200.0
    - github.com/aws/aws-sdk-go-v2/config v1.3.0

**Comment by mmmorris1975** [comment]
Hello!  If I am reading your description correctly, it seems you are trying to use this library as an SSH client.  It's not intended to be used in that manner.  The intent of this library's SSHSession feature is for developing programs which would be used in the `ProxyCommand` directive in the ssh_config file (see https://github.com/mmmorris1975/ssm-session-client#ssh) and avoiding dependencies on the awscli (and optionally the session-manager-plugin).

If you are looking for an golang library for an SSH client, I would check out https://pkg.go.dev/golang.org/x/crypto/ssh

**Comment by danquack** [comment]
That library didn't have a ProxyCommand option, I've only seen implementation of ssh tunneling, none of command. I was hoping that I could use this as a replacement. Thanks for the info though!
