### ISSUE TITLE
Execute a script before starting shell connection.

### ISSUE THREAD

**Issue by ananthb** [mmmorris1975/ssm-session-client#3]
I'd like the ability to execute a command before handing control of the shell over to the user. Would it make sense to extend StartShell with a new arg, or create a new function?

**Comment by mmmorris1975** [comment]
Thank you for the suggestion.  Does something like the changes in d52d35c7838895008aa0ea89ef30bef67f2c4ccf look like what you are requesting?

**Comment by ananthb** [comment]
That's exactly what I was thinking of!

**Comment by mmmorris1975** [comment]
Released in [v0.201.0](https://github.com/mmmorris1975/ssm-session-client/tree/v0.201.0)

**Comment by ananthb** [comment]
Awesome!

**Comment by ananthb** [comment]
Works exactly as I'd hoped it would.
