### ISSUE TITLE
Consider using AWS session-manager-plugin

### ISSUE THREAD

**Issue by mmmorris1975** [mmmorris1975/ssm-session-client#7]
AWS released the [source code for the session manager plugin to Github](https://github.com/aws/session-manager-plugin), around 6 months after we created this.  We could potentially replace all of the "guts" of this module with the AWS code, and leave the stuff we're wrapping around the SSM websocket stuff (host resolution, initial AWS requests).  Could possibly work around some of the fragility of the existing code base, will probably get port forwarding multiplexing, and features/fixes will automatically come as AWS updates their code.

**Comment by boris-smidt-klarrio** [comment]
It seems that using the plugin code directly gives issues that they set the version.go from there build pipline enabling new features. But when you include it directly in your code you can't change the 'version' causing issues.

I've also seen that the aws-plugin uses very outdated library versions causing build issues. (a deprecated UUID, lib with a version before v1).


Maybe it would be better to fork it and fix these issues and make it use proper mod file.
Or integrate the direct CLI call.
